// Deterministic, public test vectors generated by the actual Go relay package.
// The key below is a fixture, never a user or production credential.
package main

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"

	"github.com/Nathandela/swarm/internal/remote/relay"
)

func b64(b []byte) string { return base64.StdEncoding.EncodeToString(b) }

func main() {
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i)
	}
	key := ed25519.NewKeyFromSeed(seed)
	pub := key.Public().(ed25519.PublicKey)
	rid := relay.RoutingID(pub)
	nonce := []byte("public-fixture-nonce\x00with-boundary")
	ceremony := "public-fixture-ceremony"
	auth := relay.AuthChallengeMessage(nonce, rid)
	consent := relay.ConsentMessage(ceremony, rid)
	sig := ed25519.Sign(key, consent)
	credential := relay.MarshalConsent(ceremony, sig)
	parsed, parsedSig, err := relay.ParseConsent(credential)
	if err != nil || parsed != ceremony || !bytes.Equal(sig, parsedSig) {
		panic("consent roundtrip")
	}
	var frame bytes.Buffer
	payload := []byte(`{"op":"mailbox_ack","cursor":18446744073709551615}`)
	if err := relay.WriteFrame(&frame, relay.MsgRelay, payload); err != nil {
		panic(err)
	}
	vector := map[string]any{
		"pub": b64(pub), "rid": rid, "nonce": b64(nonce), "ceremony": ceremony,
		"auth": b64(auth), "authSignature": b64(ed25519.Sign(key, auth)),
		"consent": b64(consent), "consentSignature": b64(sig), "credential": b64(credential),
		"frame": b64(frame.Bytes()), "maxFrame": relay.MaxFrame, "maxCursor": fmt.Sprint(^uint64(0)),
	}
	if err := json.NewEncoder(os.Stdout).Encode(vector); err != nil {
		panic(err)
	}
}
