// Package verify_test is slice S19's fence on PB-E2E-3.
//
//	"Evidence files per repo convention with a RED-first run per slice, and each evidence file
//	 states WHAT IT PROVES, not merely that it exists."
//
// It is a test-only package (no non-test Go files), mirroring mobile/conformance: it gates a
// checked-in artifact rather than any code, so it has nothing to ship.
//
// WHY IT IS NOT PART OF THE TRACEABILITY GENERATOR. docs/verification/remote-phaseB-traceability.md
// is generated by scripts/phaseb-traceability.py and is explicit about what its own numbers
// mean: "*Evidenced* is MEASURED: the evidence file is on disk." That is exactly the weaker
// statement PB-E2E-3 was written to reject -- "merely that it exists" is its own wording -- so a
// count of 130/130 evidenced is compatible with an evidence file that has never heard of the
// requirement it is cited for. The generator cannot fence itself; this does.
//
// WHAT IT CAN AND CANNOT DECIDE. Naming a requirement is NECESSARY and not sufficient: a file
// can name one and prove nothing about it, and no regular expression settles that. The
// qualitative half of PB-E2E-3 -- does this file's evidence actually establish this
// requirement's criterion -- is a reading, and S19 reports it as findings. What is mechanical
// is the floor, and today thirteen shipped requirements are below it.
package verify_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// traceRow matches one row of the generated per-requirement table:
//
//	| PB-APP-2 | S16 | shipped | `docs/verification/remote-phaseB-s16-evidence.md` |
var traceRow = regexp.MustCompile(`^\|\s*(PB-[A-Z0-9]+-\d+)\s*\|\s*(\S+)\s*\|\s*(\w+)\s*\|\s*` +
	"`?([^`|]*)`?" + `\s*\|`)

// TestPBE2E3_EveryShippedRequirementsEvidenceFileNamesIt is the floor.
//
// A requirement whose cited evidence file never mentions it has no durable record an auditor
// can read: the row asserts a file, the file asserts nothing, and the two are only connected by
// the generator's own bookkeeping. That is the shape the traceability doc's own preamble warns
// about one column over ("*Shipped* is the orchestrator ASSERTING that a slice landed ... no
// code checks it"), applied to the column it presents as measured.
//
// IT HAS A CONTROL AGAINST VACUITY BUILT IN: the same walk counts the rows it accepted. A parse
// that matched nothing would satisfy "no violations" perfectly, which is how a table-reading
// guard dies silently when the table's formatting changes.
func TestPBE2E3_EveryShippedRequirementsEvidenceFileNamesIt(t *testing.T) {
	root := repoRoot(t)
	body, err := os.ReadFile(filepath.Join(root, "docs", "verification", "remote-phaseB-traceability.md"))
	if err != nil {
		t.Fatalf("PB-E2E-3: cannot read the traceability table: %v", err)
	}

	checked := 0
	for _, line := range strings.Split(string(body), "\n") {
		m := traceRow.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		req, slice, status, evidence := m[1], m[2], m[3], strings.TrimSpace(m[4])
		if status != "shipped" || evidence == "" || evidence == "—" {
			continue
		}
		checked++
		file, err := os.ReadFile(filepath.Join(root, evidence))
		if err != nil {
			t.Errorf("PB-E2E-3: %s (%s) is shipped and cites %s, which cannot be read: %v",
				req, slice, evidence, err)
			continue
		}
		if !strings.Contains(string(file), req) {
			t.Errorf("PB-E2E-3: %s (%s) is shipped and cites %s, which never names it. The "+
				"traceability count measures the file's EXISTENCE, which is the weaker statement "+
				"this requirement rejects in as many words", req, slice, evidence)
		}
	}
	if checked < 100 {
		t.Fatalf("PB-E2E-3: only %d shipped rows were parsed out of the traceability table; the "+
			"row pattern no longer matches it, so this guard was measuring nothing", checked)
	}
}

// repoRoot walks up to the directory holding go.mod, so the gate survives being moved.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("no go.mod found walking up from the test working directory")
		}
		dir = parent
	}
}
