# EXAMPLE Homebrew cask formula (E13.3) — committed for reference only. This is
# NOT installed by this repo and is NOT the live tap: it is a copy of what
# `goreleaser release` (driven by .goreleaser.yaml's homebrew_casks: section)
# actually writes to the Nathandela/homebrew-swarm tap repo on a real tagged
# release, captured from a local `goreleaser release --snapshot --clean
# --skip=publish,before,validate,announce` dry run so it stays honest with the
# real generator output. goreleaser regenerates and pushes the real file itself
# — never hand-edit a copy in the tap repo.
#
# The two `binary` lines are the point of this file: the swarm archive carries
# BOTH deployables, and a cask links onto PATH only what it declares. Without
# the config's `binaries:` list this file said `binary "swarm"` alone, and
# swarm-remote was downloaded into the Caskroom and never linked — so on every
# Homebrew machine `swarm remote init` could not resolve its gateway and
# installed no supervision unit (PB-LIFE-1/-2/-6).
#
# Note on the sha256 values below: a goreleaser build embeds a build
# timestamp (the {{.Date}} ldflag), so re-running the same snapshot command
# against identical source produces DIFFERENT archive checksums every time —
# this file's hashes will not match your own local rebuild, and that is
# expected, not drift to chase.
#
# Once the tap repo exists, install with:
#   brew install --cask Nathandela/swarm/swarm
# This file was generated by GoReleaser. DO NOT EDIT.
cask "swarm" do
  version "0.2.0-SNAPSHOT-6de055e"

  on_macos do
    on_intel do
      sha256 "9b2984caafbdff70871d82907f98a639f39b9cd423c14ab848727688286aa1d6"
      url "https://github.com/Nathandela/swarm/releases/download/v0.2.0/swarm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdc0f9f808457bdcc1909f614a5ab0505d4883a6e6167fd7a77a12a3c5fa77b1"
      url "https://github.com/Nathandela/swarm/releases/download/v0.2.0/swarm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da57a5be81f2ada5c9d23ee01f3f479e8d008677c2a2a0b4ca461515a0fd3e4c"
      url "https://github.com/Nathandela/swarm/releases/download/v0.2.0/swarm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a6d8ea7c8274030072d982ea59cc32330ed8eeb7e60b9abe497c45dc07f9d72"
      url "https://github.com/Nathandela/swarm/releases/download/v0.2.0/swarm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "swarm"
  desc "Every coding agent on your machine, in one keyboard-driven terminal view"
  homepage "https://github.com/Nathandela/swarm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swarm"
  binary "swarm-remote"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
