package gate

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/Nathandela/swarm/internal/phonecore"
)

// gateSealer stands in for the Android-Keystore-backed KEK the handset supplies: a real
// AEAD under a key the Go core never sees. It is SETUP ONLY -- no assertion below moves --
// and it is required because phonecore.Resume fails closed with no sealer rather than
// writing key material in the clear (ADR-007 B18(c)). Handing it in is also what makes the
// assertions meaningful: they read the bytes the core actually wrote, so a seam that sealed
// nothing still leaves the material verbatim on disk.
type gateSealer struct{ kek []byte }

func newGateSealer(t *testing.T) *gateSealer {
	t.Helper()
	kek := make([]byte, 32)
	if _, err := rand.Read(kek); err != nil {
		t.Fatalf("generating a Keystore-stand-in KEK: %v", err)
	}
	return &gateSealer{kek: kek}
}

func (s *gateSealer) gcm() (cipher.AEAD, error) {
	block, err := aes.NewCipher(s.kek)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

func (s *gateSealer) Seal(plaintext []byte) ([]byte, error) {
	g, err := s.gcm()
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, g.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return nil, err
	}
	return g.Seal(nonce, nonce, plaintext, nil), nil
}

func (s *gateSealer) Open(sealed []byte) ([]byte, error) {
	g, err := s.gcm()
	if err != nil {
		return nil, err
	}
	if len(sealed) < g.NonceSize() {
		return nil, errors.New("gate: sealed blob too short")
	}
	return g.Open(nil, sealed[:g.NonceSize()], sealed[g.NonceSize():], nil)
}

// PB-SEC-1 -- "Key material at rest is sealed under an Android-Keystore-backed KEK per the
// PB-KEY-1 custody contract and the PB-KEY-2 tier split."
//
// Criterion: "Persisted blob is not the raw key and does not decrypt without the keystore
// key."
//
// WHY THIS TEST IS IN GO AND NOT IN KOTLIN. The Kotlin custody layer can declare where key
// material lives and what seals it, and android/app/src/test/.../SealedStoreTest asserts
// against that declaration. A declaration can be wrong. These two tests read the bytes the
// phone core actually writes into the app's private data directory, so they cannot be
// satisfied by declaring anything -- which is what PB-SEC-1's criterion asks for.
//
// Both are expected to FAIL until the phone core's state directory is sealed. That is the
// finding, not a defect in the tests: nothing in the Android slice's scope can seal a file
// that Go opens for itself at Resume, and the facade (frozen since S8, pinned by
// mobile/testdata/exported_surface.golden) has no verb for it. S15's PB-STATE-6 needs the
// same mechanism, so it wants deciding once.

// TestPBSEC1_DeviceRoleKeysAreNotPersistedInTheClear. crypto.NewFileKeyStore writes the four
// device private scalars to <stateDir>/device.key as 128 raw bytes, 0600
// (internal/remote/crypto/keystore.go). 0600 is a filesystem permission, not a seal: it is
// worth nothing against ADB backup, a restored image, or any path that reads the app's data
// directory. PB-KEY-5 assigns each of these four roles a custody tier precisely so that they
// are NOT all reachable at once.
//
// The material is GENERATED by the core rather than seeded. It used to be seeded as the
// pre-seam 128 raw bytes and adopted at Resume, and that adoption was itself the hole: a
// layout with no public half cannot be authenticated, so one write to the app's private data
// directory made the phone adopt attacker-held privates. It is now REFUSED, so the exactness
// the assertions need comes from the other direction -- the container is opened with the very
// KEKs the core sealed under, which is also what "does not decrypt without the keystore key"
// means from the reading side.
func TestPBSEC1_DeviceRoleKeysAreNotPersistedInTheClear(t *testing.T) {
	dir := t.TempDir()
	wake, content := newGateSealer(t), newGateSealer(t)

	if _, err := phonecore.Resume(phonecore.Config{
		Dir: dir, Machine: "m",
		WakeSealer: wake, ContentSealer: content,
	}); err != nil {
		t.Fatalf("phonecore.Resume: %v", err)
	}

	body, err := os.ReadFile(filepath.Join(dir, "device.key"))
	if err != nil {
		t.Fatalf("PB-SEC-1: reading the persisted device keys: %v", err)
	}
	if len(body) == 0 {
		t.Fatal("PB-SEC-1: device.key is empty; every assertion below would pass vacuously")
	}

	// The container's on-disk shape, spelled out here for the same reason the file name is:
	// this test reads the BYTES the core wrote, so it cannot be satisfied by any declaration.
	var f struct {
		Content []byte `json:"content"` // noise-static || recipient || command-sign seed
		Wake    []byte `json:"wake"`    // relay-auth seed
	}
	if err := json.Unmarshal(body, &f); err != nil {
		t.Fatalf("PB-SEC-1: device.key is not the sealed container this test reads: %v", err)
	}
	contentTier, err := content.Open(f.Content)
	if err != nil {
		t.Fatalf("PB-SEC-1: the content tier does not open under the KEK it was sealed with: %v", err)
	}
	wakeTier, err := wake.Open(f.Wake)
	if err != nil {
		t.Fatalf("PB-SEC-1: the wake tier does not open under the KEK it was sealed with: %v", err)
	}
	if len(contentTier) != 96 || len(wakeTier) != 32 {
		t.Fatalf("PB-SEC-1: the sealed tiers hold %d + %d bytes, want 96 + 32 (the four device "+
			"private scalars); every assertion below would pass vacuously", len(contentTier), len(wakeTier))
	}

	for _, role := range []struct {
		name  string
		bytes []byte
		tier  string
	}{
		{"NoiseStatic", contentTier[0:32], "content"},
		{"Recipient", contentTier[32:64], "content"},
		{"CommandSign", contentTier[64:96], "content"},
		{"RelayAuth", wakeTier, "wake"},
	} {
		if bytes.Contains(body, role.bytes) {
			t.Errorf("PB-SEC-1: the %s private key (PB-KEY-5 %s tier) sits verbatim in "+
				"%s. At rest it must be sealed under an Android-Keystore-backed KEK; "+
				"0600 is a filesystem permission, not a seal",
				role.name, role.tier, filepath.Join("<stateDir>", "device.key"))
		}
	}
}

// TestPBSEC1_EpochKeysAreNotPersistedInTheClear. App.InstallContentKey copies the unwrapped
// content key into the durable State and calls Save (mobile/app.go), and the state blob is
// plain JSON with `wake_key` and `content_key` as base64 fields
// (internal/phonecore/state.go:176-177, 409-410). So the one artifact the whole two-tier
// design is built around is written to disk in the clear, both tiers together in one file --
// which also collapses PB-KEY-2's split at rest, since a single file cannot be gated two
// ways.
func TestPBSEC1_EpochKeysAreNotPersistedInTheClear(t *testing.T) {
	dir := t.TempDir()
	core, err := phonecore.Resume(phonecore.Config{
		Dir: dir, Machine: "m",
		WakeSealer: newGateSealer(t), ContentSealer: newGateSealer(t),
	})
	if err != nil {
		t.Fatalf("phonecore.Resume: %v", err)
	}

	st := core.State()
	for i := range st.Keys.WakeKey {
		st.Keys.WakeKey[i] = byte(0x11 + i)
		st.Keys.ContentKey[i] = byte(0x55 + i)
	}
	if err := core.Save(st); err != nil {
		t.Fatalf("saving state: %v", err)
	}

	body, err := os.ReadFile(filepath.Join(dir, phonecore.StateFileName))
	if err != nil {
		t.Fatalf("PB-SEC-1: reading the persisted state blob: %v", err)
	}
	if len(body) == 0 {
		t.Fatal("PB-SEC-1: the state blob is empty; the assertions below would pass vacuously")
	}

	// JSON encodes []byte as base64, so search for both forms rather than assuming one.
	for _, key := range []struct {
		name  string
		bytes []byte
		tier  string
	}{
		{"WakeKey", st.Keys.WakeKey[:], "wake"},
		{"ContentKey", st.Keys.ContentKey[:], "content"},
	} {
		if bytes.Contains(body, key.bytes) || bytes.Contains(body, []byte(base64Std(key.bytes))) {
			t.Errorf("PB-SEC-1: the epoch %s (PB-KEY-2 %s tier) is recoverable verbatim from "+
				"%s. PB-KEY-2 gates the content tier behind user authentication; a plaintext "+
				"copy on disk is reachable without it",
				key.name, key.tier, filepath.Join("<stateDir>", phonecore.StateFileName))
		}
	}
}
